// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/auth-service/proto/token/token.proto

package token

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_93424b2924ebe966, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_93424b2924ebe966, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Validate token model
type PayloadValidate struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayloadValidate) Reset()         { *m = PayloadValidate{} }
func (m *PayloadValidate) String() string { return proto.CompactTextString(m) }
func (*PayloadValidate) ProtoMessage()    {}
func (*PayloadValidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_93424b2924ebe966, []int{2}
}
func (m *PayloadValidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayloadValidate.Unmarshal(m, b)
}
func (m *PayloadValidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayloadValidate.Marshal(b, m, deterministic)
}
func (dst *PayloadValidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayloadValidate.Merge(dst, src)
}
func (m *PayloadValidate) XXX_Size() int {
	return xxx_messageInfo_PayloadValidate.Size(m)
}
func (m *PayloadValidate) XXX_DiscardUnknown() {
	xxx_messageInfo_PayloadValidate.DiscardUnknown(m)
}

var xxx_messageInfo_PayloadValidate proto.InternalMessageInfo

func (m *PayloadValidate) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ResponseValidation struct {
	Success              bool                          `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Claim                *ResponseValidation_ClaimData `protobuf:"bytes,2,opt,name=Claim,proto3" json:"Claim,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ResponseValidation) Reset()         { *m = ResponseValidation{} }
func (m *ResponseValidation) String() string { return proto.CompactTextString(m) }
func (*ResponseValidation) ProtoMessage()    {}
func (*ResponseValidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_93424b2924ebe966, []int{3}
}
func (m *ResponseValidation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseValidation.Unmarshal(m, b)
}
func (m *ResponseValidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseValidation.Marshal(b, m, deterministic)
}
func (dst *ResponseValidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseValidation.Merge(dst, src)
}
func (m *ResponseValidation) XXX_Size() int {
	return xxx_messageInfo_ResponseValidation.Size(m)
}
func (m *ResponseValidation) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseValidation.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseValidation proto.InternalMessageInfo

func (m *ResponseValidation) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResponseValidation) GetClaim() *ResponseValidation_ClaimData {
	if m != nil {
		return m.Claim
	}
	return nil
}

type ResponseValidation_ClaimData struct {
	Audience             string                                 `protobuf:"bytes,1,opt,name=Audience,proto3" json:"Audience,omitempty"`
	ExpiresAt            int64                                  `protobuf:"varint,2,opt,name=ExpiresAt,proto3" json:"ExpiresAt,omitempty"`
	IssuedAt             int64                                  `protobuf:"varint,3,opt,name=IssuedAt,proto3" json:"IssuedAt,omitempty"`
	Issuer               string                                 `protobuf:"bytes,4,opt,name=Issuer,proto3" json:"Issuer,omitempty"`
	NotBefore            int64                                  `protobuf:"varint,5,opt,name=NotBefore,proto3" json:"NotBefore,omitempty"`
	Subject              string                                 `protobuf:"bytes,6,opt,name=Subject,proto3" json:"Subject,omitempty"`
	DeviceID             string                                 `protobuf:"bytes,7,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	User                 *ResponseValidation_ClaimData_UserData `protobuf:"bytes,8,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ResponseValidation_ClaimData) Reset()         { *m = ResponseValidation_ClaimData{} }
func (m *ResponseValidation_ClaimData) String() string { return proto.CompactTextString(m) }
func (*ResponseValidation_ClaimData) ProtoMessage()    {}
func (*ResponseValidation_ClaimData) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_93424b2924ebe966, []int{3, 0}
}
func (m *ResponseValidation_ClaimData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseValidation_ClaimData.Unmarshal(m, b)
}
func (m *ResponseValidation_ClaimData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseValidation_ClaimData.Marshal(b, m, deterministic)
}
func (dst *ResponseValidation_ClaimData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseValidation_ClaimData.Merge(dst, src)
}
func (m *ResponseValidation_ClaimData) XXX_Size() int {
	return xxx_messageInfo_ResponseValidation_ClaimData.Size(m)
}
func (m *ResponseValidation_ClaimData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseValidation_ClaimData.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseValidation_ClaimData proto.InternalMessageInfo

func (m *ResponseValidation_ClaimData) GetAudience() string {
	if m != nil {
		return m.Audience
	}
	return ""
}

func (m *ResponseValidation_ClaimData) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *ResponseValidation_ClaimData) GetIssuedAt() int64 {
	if m != nil {
		return m.IssuedAt
	}
	return 0
}

func (m *ResponseValidation_ClaimData) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *ResponseValidation_ClaimData) GetNotBefore() int64 {
	if m != nil {
		return m.NotBefore
	}
	return 0
}

func (m *ResponseValidation_ClaimData) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ResponseValidation_ClaimData) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *ResponseValidation_ClaimData) GetUser() *ResponseValidation_ClaimData_UserData {
	if m != nil {
		return m.User
	}
	return nil
}

type ResponseValidation_ClaimData_UserData struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseValidation_ClaimData_UserData) Reset()         { *m = ResponseValidation_ClaimData_UserData{} }
func (m *ResponseValidation_ClaimData_UserData) String() string { return proto.CompactTextString(m) }
func (*ResponseValidation_ClaimData_UserData) ProtoMessage()    {}
func (*ResponseValidation_ClaimData_UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_token_93424b2924ebe966, []int{3, 0, 0}
}
func (m *ResponseValidation_ClaimData_UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseValidation_ClaimData_UserData.Unmarshal(m, b)
}
func (m *ResponseValidation_ClaimData_UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseValidation_ClaimData_UserData.Marshal(b, m, deterministic)
}
func (dst *ResponseValidation_ClaimData_UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseValidation_ClaimData_UserData.Merge(dst, src)
}
func (m *ResponseValidation_ClaimData_UserData) XXX_Size() int {
	return xxx_messageInfo_ResponseValidation_ClaimData_UserData.Size(m)
}
func (m *ResponseValidation_ClaimData_UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseValidation_ClaimData_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseValidation_ClaimData_UserData proto.InternalMessageInfo

func (m *ResponseValidation_ClaimData_UserData) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "token.Request")
	proto.RegisterType((*Response)(nil), "token.Response")
	proto.RegisterType((*PayloadValidate)(nil), "token.PayloadValidate")
	proto.RegisterType((*ResponseValidation)(nil), "token.ResponseValidation")
	proto.RegisterType((*ResponseValidation_ClaimData)(nil), "token.ResponseValidation.ClaimData")
	proto.RegisterType((*ResponseValidation_ClaimData_UserData)(nil), "token.ResponseValidation.ClaimData.UserData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TokenHandlerClient is the client API for TokenHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenHandlerClient interface {
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ValidateToken(ctx context.Context, in *PayloadValidate, opts ...grpc.CallOption) (*ResponseValidation, error)
}

type tokenHandlerClient struct {
	cc *grpc.ClientConn
}

func NewTokenHandlerClient(cc *grpc.ClientConn) TokenHandlerClient {
	return &tokenHandlerClient{cc}
}

func (c *tokenHandlerClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/token.TokenHandler/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenHandlerClient) ValidateToken(ctx context.Context, in *PayloadValidate, opts ...grpc.CallOption) (*ResponseValidation, error) {
	out := new(ResponseValidation)
	err := c.cc.Invoke(ctx, "/token.TokenHandler/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenHandlerServer is the server API for TokenHandler service.
type TokenHandlerServer interface {
	Hello(context.Context, *Request) (*Response, error)
	ValidateToken(context.Context, *PayloadValidate) (*ResponseValidation, error)
}

func RegisterTokenHandlerServer(s *grpc.Server, srv TokenHandlerServer) {
	s.RegisterService(&_TokenHandler_serviceDesc, srv)
}

func _TokenHandler_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenHandlerServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.TokenHandler/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenHandlerServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenHandler_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayloadValidate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenHandlerServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.TokenHandler/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenHandlerServer).ValidateToken(ctx, req.(*PayloadValidate))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "token.TokenHandler",
	HandlerType: (*TokenHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _TokenHandler_Hello_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _TokenHandler_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/auth-service/proto/token/token.proto",
}

func init() {
	proto.RegisterFile("api/auth-service/proto/token/token.proto", fileDescriptor_token_93424b2924ebe966)
}

var fileDescriptor_token_93424b2924ebe966 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0xa5, 0x69, 0xd3, 0xa6, 0xf7, 0xbd, 0xd7, 0xc2, 0xf0, 0x28, 0xf3, 0xc2, 0x5b, 0x94, 0x56,
	0x30, 0x0b, 0x4d, 0xa1, 0xae, 0xdc, 0xd9, 0x1a, 0xa1, 0x59, 0x28, 0x12, 0x3f, 0xf6, 0xd3, 0xe4,
	0xaa, 0xd1, 0x98, 0x89, 0x99, 0x89, 0x28, 0xf8, 0x3f, 0xfc, 0x11, 0xfe, 0x49, 0xc9, 0x4c, 0x12,
	0xa1, 0xa2, 0xb8, 0x29, 0x3d, 0x37, 0xe7, 0x9e, 0x73, 0xe7, 0xdc, 0x0b, 0x0e, 0xcb, 0xe2, 0x19,
	0x2b, 0xe4, 0xcd, 0xae, 0xc0, 0xfc, 0x31, 0x0e, 0x71, 0x96, 0xe5, 0x5c, 0xf2, 0x99, 0xe4, 0x77,
	0x98, 0xea, 0x5f, 0x57, 0x55, 0x88, 0xa9, 0xc0, 0x64, 0x0a, 0xbd, 0x00, 0x1f, 0x0a, 0x14, 0x92,
	0x50, 0xe8, 0x1d, 0xa3, 0x10, 0xec, 0x1a, 0x69, 0x6b, 0xdc, 0x72, 0xfa, 0x41, 0x0d, 0x27, 0x5b,
	0x60, 0x05, 0x28, 0x32, 0x9e, 0x0a, 0xfc, 0x86, 0xb5, 0x0d, 0xc3, 0x53, 0xf6, 0x9c, 0x70, 0x16,
	0x5d, 0xb2, 0x24, 0x8e, 0x98, 0x44, 0xf2, 0x17, 0xcc, 0xf3, 0xd2, 0xa6, 0xa2, 0x6a, 0x30, 0x79,
	0x6d, 0x03, 0xa9, 0xf5, 0x2a, 0x6a, 0xcc, 0xd3, 0x52, 0xf9, 0xac, 0x08, 0x43, 0x14, 0x42, 0xd1,
	0xad, 0xa0, 0x86, 0x64, 0x1f, 0xcc, 0xc3, 0x84, 0xc5, 0xf7, 0xd4, 0x18, 0xb7, 0x9c, 0x5f, 0xf3,
	0xa9, 0xab, 0x1f, 0xf2, 0x59, 0xc3, 0x55, 0x34, 0x8f, 0x49, 0x16, 0xe8, 0x0e, 0xfb, 0xcd, 0x80,
	0x7e, 0x53, 0x24, 0x36, 0x58, 0x8b, 0x22, 0x8a, 0x31, 0x0d, 0xeb, 0xe9, 0x1b, 0x4c, 0xfe, 0x43,
	0xff, 0xe8, 0x29, 0x8b, 0x73, 0x14, 0x0b, 0xa9, 0x8c, 0xda, 0xc1, 0x47, 0xa1, 0xec, 0xf4, 0x85,
	0x28, 0x30, 0x5a, 0x48, 0xda, 0x56, 0x1f, 0x1b, 0x4c, 0x46, 0xd0, 0x55, 0xff, 0x73, 0xda, 0x51,
	0x9a, 0x15, 0x2a, 0x15, 0x4f, 0xb8, 0x5c, 0xe2, 0x15, 0xcf, 0x91, 0x9a, 0x5a, 0xb1, 0x29, 0xe8,
	0xe7, 0xae, 0x6f, 0x31, 0x94, 0xb4, 0xab, 0x83, 0xac, 0x60, 0xe9, 0xe5, 0x61, 0xb9, 0x3c, 0xdf,
	0xa3, 0x3d, 0x3d, 0x65, 0x8d, 0xc9, 0x01, 0x74, 0x2e, 0x04, 0xe6, 0xd4, 0x52, 0x49, 0xec, 0xfc,
	0x20, 0x09, 0xb7, 0xe4, 0xab, 0x48, 0x54, 0xa7, 0x6d, 0x83, 0x55, 0x57, 0xc8, 0x00, 0x0c, 0xdf,
	0xab, 0x92, 0x30, 0x7c, 0x6f, 0xfe, 0x02, 0xbf, 0xd5, 0x8a, 0x56, 0x2c, 0x8d, 0x12, 0xcc, 0x89,
	0x03, 0xe6, 0x0a, 0x93, 0x84, 0x93, 0x41, 0x63, 0xa4, 0x6e, 0xc5, 0x1e, 0x6e, 0x18, 0x93, 0x25,
	0xfc, 0xa9, 0xb7, 0xae, 0x14, 0xc8, 0xa8, 0x62, 0x6c, 0x9c, 0x84, 0xfd, 0xef, 0xcb, 0x91, 0xd7,
	0x5d, 0x75, 0x99, 0x7b, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x31, 0x38, 0xcd, 0xc5, 0x02,
	0x00, 0x00,
}
