// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BasicAuthValidator is an autogenerated mock type for the BasicAuthValidator type
type BasicAuthValidator struct {
	mock.Mock
}

// ValidateBasic provides a mock function with given fields: username, password
func (_m *BasicAuthValidator) ValidateBasic(username string, password string) error {
	ret := _m.Called(username, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBasicAuthValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewBasicAuthValidator creates a new instance of BasicAuthValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBasicAuthValidator(t mockConstructorTestingTNewBasicAuthValidator) *BasicAuthValidator {
	mock := &BasicAuthValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
