// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/golangid/candi/codebase/interfaces"
	mock "github.com/stretchr/testify/mock"

	types "github.com/golangid/candi/codebase/factory/types"
)

// Broker is an autogenerated mock type for the Broker type
type Broker struct {
	mock.Mock
}

// Disconnect provides a mock function with given fields: ctx
func (_m *Broker) Disconnect(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetConfiguration provides a mock function with given fields:
func (_m *Broker) GetConfiguration() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// GetName provides a mock function with given fields:
func (_m *Broker) GetName() types.Worker {
	ret := _m.Called()

	var r0 types.Worker
	if rf, ok := ret.Get(0).(func() types.Worker); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.Worker)
	}

	return r0
}

// GetPublisher provides a mock function with given fields:
func (_m *Broker) GetPublisher() interfaces.Publisher {
	ret := _m.Called()

	var r0 interfaces.Publisher
	if rf, ok := ret.Get(0).(func() interfaces.Publisher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.Publisher)
		}
	}

	return r0
}

// Health provides a mock function with given fields:
func (_m *Broker) Health() map[string]error {
	ret := _m.Called()

	var r0 map[string]error
	if rf, ok := ret.Get(0).(func() map[string]error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]error)
		}
	}

	return r0
}

// NewBroker creates a new instance of Broker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *Broker {
	mock := &Broker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
