// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	amqp "github.com/streadway/amqp"

	interfaces "pkg.agungdp.dev/candi/codebase/interfaces"

	mock "github.com/stretchr/testify/mock"

	sarama "github.com/Shopify/sarama"

	types "pkg.agungdp.dev/candi/codebase/factory/types"
)

// Broker is an autogenerated mock type for the Broker type
type Broker struct {
	mock.Mock
}

// Disconnect provides a mock function with given fields: ctx
func (_m *Broker) Disconnect(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetKafkaClient provides a mock function with given fields:
func (_m *Broker) GetKafkaClient() sarama.Client {
	ret := _m.Called()

	var r0 sarama.Client
	if rf, ok := ret.Get(0).(func() sarama.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sarama.Client)
		}
	}

	return r0
}

// GetRabbitMQConn provides a mock function with given fields:
func (_m *Broker) GetRabbitMQConn() *amqp.Connection {
	ret := _m.Called()

	var r0 *amqp.Connection
	if rf, ok := ret.Get(0).(func() *amqp.Connection); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp.Connection)
		}
	}

	return r0
}

// Health provides a mock function with given fields:
func (_m *Broker) Health() map[string]error {
	ret := _m.Called()

	var r0 map[string]error
	if rf, ok := ret.Get(0).(func() map[string]error); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]error)
		}
	}

	return r0
}

// Publisher provides a mock function with given fields: _a0
func (_m *Broker) Publisher(_a0 types.Worker) interfaces.Publisher {
	ret := _m.Called(_a0)

	var r0 interfaces.Publisher
	if rf, ok := ret.Get(0).(func(types.Worker) interfaces.Publisher); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.Publisher)
		}
	}

	return r0
}
