// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GraphQLHandler is an autogenerated mock type for the GraphQLHandler type
type GraphQLHandler struct {
	mock.Mock
}

// Mutation provides a mock function with given fields:
func (_m *GraphQLHandler) Mutation() any {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mutation")
	}

	var r0 any
	if rf, ok := ret.Get(0).(func() any); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	return r0
}

// Query provides a mock function with given fields:
func (_m *GraphQLHandler) Query() any {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 any
	if rf, ok := ret.Get(0).(func() any); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	return r0
}

// Schema provides a mock function with given fields:
func (_m *GraphQLHandler) Schema() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Schema")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Subscription provides a mock function with given fields:
func (_m *GraphQLHandler) Subscription() any {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscription")
	}

	var r0 any
	if rf, ok := ret.Get(0).(func() any); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	return r0
}

// NewGraphQLHandler creates a new instance of GraphQLHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGraphQLHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *GraphQLHandler {
	mock := &GraphQLHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
