// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	context "context"

	candishared "github.com/golangid/candi/candishared"

	graphql_gotypes "github.com/golangid/graphql-go/types"

	http "net/http"

	mock "github.com/stretchr/testify/mock"

	types "github.com/golangid/candi/codebase/factory/types"
)

// Middleware is an autogenerated mock type for the Middleware type
type Middleware struct {
	mock.Mock
}

// Basic provides a mock function with given fields: ctx, authKey
func (_m *Middleware) Basic(ctx context.Context, authKey string) error {
	ret := _m.Called(ctx, authKey)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, authKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Bearer provides a mock function with given fields: ctx, token
func (_m *Middleware) Bearer(ctx context.Context, token string) (*candishared.TokenClaim, error) {
	ret := _m.Called(ctx, token)

	var r0 *candishared.TokenClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*candishared.TokenClaim, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *candishared.TokenClaim); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*candishared.TokenClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GRPCBasicAuth provides a mock function with given fields: ctx
func (_m *Middleware) GRPCBasicAuth(ctx context.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GRPCBearerAuth provides a mock function with given fields: ctx
func (_m *Middleware) GRPCBearerAuth(ctx context.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GRPCMultipleAuth provides a mock function with given fields: ctx
func (_m *Middleware) GRPCMultipleAuth(ctx context.Context) (context.Context, error) {
	ret := _m.Called(ctx)

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GRPCPermissionACL provides a mock function with given fields: permissionCode
func (_m *Middleware) GRPCPermissionACL(permissionCode string) types.MiddlewareFunc {
	ret := _m.Called(permissionCode)

	var r0 types.MiddlewareFunc
	if rf, ok := ret.Get(0).(func(string) types.MiddlewareFunc); ok {
		r0 = rf(permissionCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.MiddlewareFunc)
		}
	}

	return r0
}

// GraphQLAuth provides a mock function with given fields: ctx, directive, input
func (_m *Middleware) GraphQLAuth(ctx context.Context, directive *graphql_gotypes.Directive, input interface{}) (context.Context, error) {
	ret := _m.Called(ctx, directive, input)

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *graphql_gotypes.Directive, interface{}) (context.Context, error)); ok {
		return rf(ctx, directive, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *graphql_gotypes.Directive, interface{}) context.Context); ok {
		r0 = rf(ctx, directive, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *graphql_gotypes.Directive, interface{}) error); ok {
		r1 = rf(ctx, directive, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GraphQLPermissionACL provides a mock function with given fields: ctx, directive, input
func (_m *Middleware) GraphQLPermissionACL(ctx context.Context, directive *graphql_gotypes.Directive, input interface{}) (context.Context, error) {
	ret := _m.Called(ctx, directive, input)

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *graphql_gotypes.Directive, interface{}) (context.Context, error)); ok {
		return rf(ctx, directive, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *graphql_gotypes.Directive, interface{}) context.Context); ok {
		r0 = rf(ctx, directive, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *graphql_gotypes.Directive, interface{}) error); ok {
		r1 = rf(ctx, directive, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPBasicAuth provides a mock function with given fields: next
func (_m *Middleware) HTTPBasicAuth(next http.Handler) http.Handler {
	ret := _m.Called(next)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// HTTPBearerAuth provides a mock function with given fields: next
func (_m *Middleware) HTTPBearerAuth(next http.Handler) http.Handler {
	ret := _m.Called(next)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// HTTPCache provides a mock function with given fields: next
func (_m *Middleware) HTTPCache(next http.Handler) http.Handler {
	ret := _m.Called(next)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// HTTPMultipleAuth provides a mock function with given fields: next
func (_m *Middleware) HTTPMultipleAuth(next http.Handler) http.Handler {
	ret := _m.Called(next)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(http.Handler) http.Handler); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}

// HTTPPermissionACL provides a mock function with given fields: permissionCode
func (_m *Middleware) HTTPPermissionACL(permissionCode string) func(http.Handler) http.Handler {
	ret := _m.Called(permissionCode)

	var r0 func(http.Handler) http.Handler
	if rf, ok := ret.Get(0).(func(string) func(http.Handler) http.Handler); ok {
		r0 = rf(permissionCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(http.Handler) http.Handler)
		}
	}

	return r0
}

// NewMiddleware creates a new instance of Middleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *Middleware {
	mock := &Middleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
