// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/golangid/candi/codebase/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// RESTHandler is an autogenerated mock type for the RESTHandler type
type RESTHandler struct {
	mock.Mock
}

// Mount provides a mock function with given fields: group
func (_m *RESTHandler) Mount(group interfaces.RESTRouter) {
	_m.Called(group)
}

// NewRESTHandler creates a new instance of RESTHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRESTHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *RESTHandler {
	mock := &RESTHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
