// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ServerHandler is an autogenerated mock type for the ServerHandler type
type ServerHandler struct {
	mock.Mock
}

// MountHandlers provides a mock function with given fields: group
func (_m *ServerHandler) MountHandlers(group interface{}) {
	_m.Called(group)
}
