// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	types "pkg.agungdp.dev/candi/codebase/factory/types"
)

// WorkerHandler is an autogenerated mock type for the WorkerHandler type
type WorkerHandler struct {
	mock.Mock
}

// MountHandlers provides a mock function with given fields: group
func (_m *WorkerHandler) MountHandlers(group *types.WorkerHandlerGroup) {
	_m.Called(group)
}
