// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	tracer "github.com/golangid/candi/tracer"
	mock "github.com/stretchr/testify/mock"
)

// FinishOptionFunc is an autogenerated mock type for the FinishOptionFunc type
type FinishOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *FinishOptionFunc) Execute(_a0 *tracer.FinishOption) {
	_m.Called(_a0)
}
