// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	taskqueueworker "github.com/golangid/candi/codebase/app/task_queue_worker"
	mock "github.com/stretchr/testify/mock"
)

// QueueStorage is an autogenerated mock type for the QueueStorage type
type QueueStorage struct {
	mock.Mock
}

// Clear provides a mock function with given fields: ctx, taskName
func (_m *QueueStorage) Clear(ctx context.Context, taskName string) {
	_m.Called(ctx, taskName)
}

// NextJob provides a mock function with given fields: ctx, taskName
func (_m *QueueStorage) NextJob(ctx context.Context, taskName string) string {
	ret := _m.Called(ctx, taskName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, taskName)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PopJob provides a mock function with given fields: ctx, taskName
func (_m *QueueStorage) PopJob(ctx context.Context, taskName string) string {
	ret := _m.Called(ctx, taskName)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, taskName)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PushJob provides a mock function with given fields: ctx, job
func (_m *QueueStorage) PushJob(ctx context.Context, job *taskqueueworker.Job) {
	_m.Called(ctx, job)
}
