// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// ServeGraphQL provides a mock function with given fields:
func (_m *Handler) ServeGraphQL() http.HandlerFunc {
	ret := _m.Called()

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func() http.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// ServePlayground provides a mock function with given fields: resp, req
func (_m *Handler) ServePlayground(resp http.ResponseWriter, req *http.Request) {
	_m.Called(resp, req)
}

// ServeVoyager provides a mock function with given fields: resp, req
func (_m *Handler) ServeVoyager(resp http.ResponseWriter, req *http.Request) {
	_m.Called(resp, req)
}
