// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// ServeGraphQL provides a mock function with given fields:
func (_m *Handler) ServeGraphQL() http.HandlerFunc {
	ret := _m.Called()

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func() http.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// ServePlayground provides a mock function with given fields: resp, req
func (_m *Handler) ServePlayground(resp http.ResponseWriter, req *http.Request) {
	_m.Called(resp, req)
}

// ServeVoyager provides a mock function with given fields: resp, req
func (_m *Handler) ServeVoyager(resp http.ResponseWriter, req *http.Request) {
	_m.Called(resp, req)
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
