// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	broker "github.com/golangid/candi/broker"
	mock "github.com/stretchr/testify/mock"
)

// RabbitMQOptionFunc is an autogenerated mock type for the RabbitMQOptionFunc type
type RabbitMQOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *RabbitMQOptionFunc) Execute(_a0 *broker.RabbitMQBroker) {
	_m.Called(_a0)
}
