// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	broker "github.com/golangid/candi/broker"
	mock "github.com/stretchr/testify/mock"
)

// RedisOptionFunc is an autogenerated mock type for the RedisOptionFunc type
type RedisOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *RedisOptionFunc) Execute(_a0 *broker.RedisBroker) {
	_m.Called(_a0)
}

// NewRedisOptionFunc creates a new instance of RedisOptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisOptionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisOptionFunc {
	mock := &RedisOptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
