// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HTTPRequest is an autogenerated mock type for the HTTPRequest type
type HTTPRequest struct {
	mock.Mock
}

// Do provides a mock function with given fields: _a0, method, url, reqBody, headers
func (_m *HTTPRequest) Do(_a0 context.Context, method string, url string, reqBody []byte, headers map[string]string) ([]byte, int, error) {
	ret := _m.Called(_a0, method, url, reqBody, headers)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte, map[string]string) []byte); ok {
		r0 = rf(_a0, method, url, reqBody, headers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte, map[string]string) int); ok {
		r1 = rf(_a0, method, url, reqBody, headers)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, []byte, map[string]string) error); ok {
		r2 = rf(_a0, method, url, reqBody, headers)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
