// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/line-chatbot/event/event.proto

package event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Filter struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Sort                 string   `protobuf:"bytes,3,opt,name=Sort,proto3" json:"Sort,omitempty"`
	OrderBy              string   `protobuf:"bytes,4,opt,name=OrderBy,proto3" json:"OrderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_7fc4bbfdcfb01740, []int{0}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Filter) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Filter) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *Filter) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type Meta struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	TotalRecords         int64    `protobuf:"varint,3,opt,name=TotalRecords,proto3" json:"TotalRecords,omitempty"`
	TotalPages           int64    `protobuf:"varint,4,opt,name=TotalPages,proto3" json:"TotalPages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_7fc4bbfdcfb01740, []int{1}
}
func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (dst *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(dst, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Meta) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Meta) GetTotalRecords() int64 {
	if m != nil {
		return m.TotalRecords
	}
	return 0
}

func (m *Meta) GetTotalPages() int64 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

type Event struct {
	ID                   string         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ReplyToken           string         `protobuf:"bytes,2,opt,name=ReplyToken,proto3" json:"ReplyToken,omitempty"`
	Type                 string         `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Timestamp            string         `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	SourceID             string         `protobuf:"bytes,5,opt,name=SourceID,proto3" json:"SourceID,omitempty"`
	SourceType           string         `protobuf:"bytes,6,opt,name=SourceType,proto3" json:"SourceType,omitempty"`
	Error                string         `protobuf:"bytes,7,opt,name=Error,proto3" json:"Error,omitempty"`
	Message              *Event_Message `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_7fc4bbfdcfb01740, []int{2}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Event) GetReplyToken() string {
	if m != nil {
		return m.ReplyToken
	}
	return ""
}

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Event) GetSourceID() string {
	if m != nil {
		return m.SourceID
	}
	return ""
}

func (m *Event) GetSourceType() string {
	if m != nil {
		return m.SourceType
	}
	return ""
}

func (m *Event) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Event) GetMessage() *Event_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type Event_Message struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	Response             string   `protobuf:"bytes,4,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event_Message) Reset()         { *m = Event_Message{} }
func (m *Event_Message) String() string { return proto.CompactTextString(m) }
func (*Event_Message) ProtoMessage()    {}
func (*Event_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_7fc4bbfdcfb01740, []int{2, 0}
}
func (m *Event_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event_Message.Unmarshal(m, b)
}
func (m *Event_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event_Message.Marshal(b, m, deterministic)
}
func (dst *Event_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event_Message.Merge(dst, src)
}
func (m *Event_Message) XXX_Size() int {
	return xxx_messageInfo_Event_Message.Size(m)
}
func (m *Event_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Event_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Event_Message proto.InternalMessageInfo

func (m *Event_Message) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Event_Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event_Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Event_Message) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type ResponseFindAll struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=Meta,proto3" json:"Meta,omitempty"`
	Events               []*Event `protobuf:"bytes,4,rep,name=Events,proto3" json:"Events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseFindAll) Reset()         { *m = ResponseFindAll{} }
func (m *ResponseFindAll) String() string { return proto.CompactTextString(m) }
func (*ResponseFindAll) ProtoMessage()    {}
func (*ResponseFindAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_7fc4bbfdcfb01740, []int{3}
}
func (m *ResponseFindAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseFindAll.Unmarshal(m, b)
}
func (m *ResponseFindAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseFindAll.Marshal(b, m, deterministic)
}
func (dst *ResponseFindAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseFindAll.Merge(dst, src)
}
func (m *ResponseFindAll) XXX_Size() int {
	return xxx_messageInfo_ResponseFindAll.Size(m)
}
func (m *ResponseFindAll) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseFindAll.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseFindAll proto.InternalMessageInfo

func (m *ResponseFindAll) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ResponseFindAll) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ResponseFindAll) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *ResponseFindAll) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Filter)(nil), "event.Filter")
	proto.RegisterType((*Meta)(nil), "event.Meta")
	proto.RegisterType((*Event)(nil), "event.Event")
	proto.RegisterType((*Event_Message)(nil), "event.Event.Message")
	proto.RegisterType((*ResponseFindAll)(nil), "event.ResponseFindAll")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventHandlerClient is the client API for EventHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventHandlerClient interface {
	FindAll(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*ResponseFindAll, error)
}

type eventHandlerClient struct {
	cc *grpc.ClientConn
}

func NewEventHandlerClient(cc *grpc.ClientConn) EventHandlerClient {
	return &eventHandlerClient{cc}
}

func (c *eventHandlerClient) FindAll(ctx context.Context, in *Filter, opts ...grpc.CallOption) (*ResponseFindAll, error) {
	out := new(ResponseFindAll)
	err := c.cc.Invoke(ctx, "/event.EventHandler/FindAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventHandlerServer is the server API for EventHandler service.
type EventHandlerServer interface {
	FindAll(context.Context, *Filter) (*ResponseFindAll, error)
}

func RegisterEventHandlerServer(s *grpc.Server, srv EventHandlerServer) {
	s.RegisterService(&_EventHandler_serviceDesc, srv)
}

func _EventHandler_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Filter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventHandlerServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event.EventHandler/FindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventHandlerServer).FindAll(ctx, req.(*Filter))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "event.EventHandler",
	HandlerType: (*EventHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _EventHandler_FindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/line-chatbot/event/event.proto",
}

func init() {
	proto.RegisterFile("api/proto/line-chatbot/event/event.proto", fileDescriptor_event_7fc4bbfdcfb01740)
}

var fileDescriptor_event_7fc4bbfdcfb01740 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xd1, 0xaa, 0xd3, 0x40,
	0x10, 0x25, 0x69, 0xd3, 0xb4, 0xd3, 0xaa, 0xb0, 0x5c, 0x24, 0x14, 0xd1, 0x12, 0x7c, 0xc8, 0x8b,
	0xad, 0xd4, 0x1f, 0x50, 0xe9, 0xbd, 0x58, 0xf0, 0xa2, 0x6c, 0xfb, 0x2a, 0x98, 0x9b, 0x0e, 0x1a,
	0x4c, 0xb2, 0x61, 0x77, 0xaf, 0xd8, 0x7f, 0xf0, 0xcb, 0xfc, 0x2a, 0x99, 0xd9, 0x4d, 0x1a, 0xf5,
	0xc9, 0x97, 0x30, 0xe7, 0x9c, 0xdd, 0x3d, 0x73, 0x76, 0x36, 0x90, 0xe5, 0x6d, 0xb9, 0x69, 0xb5,
	0xb2, 0x6a, 0x53, 0x95, 0x0d, 0xbe, 0x28, 0xbe, 0xe6, 0xf6, 0x4e, 0xd9, 0x0d, 0x7e, 0xc7, 0xc6,
	0x7f, 0xd7, 0x2c, 0x8b, 0x88, 0x41, 0xfa, 0x19, 0x26, 0x37, 0x65, 0x65, 0x51, 0x0b, 0x01, 0xe3,
	0x8f, 0xf9, 0x17, 0x4c, 0x82, 0x55, 0x90, 0x45, 0x92, 0x6b, 0x71, 0x05, 0xd1, 0xfb, 0xb2, 0x2e,
	0x6d, 0x12, 0x32, 0xe9, 0x00, 0xad, 0x3c, 0x28, 0x6d, 0x93, 0xd1, 0x2a, 0xc8, 0x66, 0x92, 0x6b,
	0x91, 0x40, 0xfc, 0x41, 0x9f, 0x50, 0xbf, 0x3d, 0x27, 0x63, 0xa6, 0x3b, 0x98, 0x5a, 0x18, 0xdf,
	0xa2, 0xcd, 0xff, 0xe3, 0xfc, 0x14, 0x16, 0x47, 0x65, 0xf3, 0x4a, 0x62, 0xa1, 0xf4, 0xc9, 0xb0,
	0xcf, 0x48, 0xfe, 0xc1, 0x89, 0xa7, 0x00, 0x8c, 0xe9, 0x18, 0xc3, 0x96, 0x23, 0x39, 0x60, 0xd2,
	0x5f, 0x21, 0x44, 0xd7, 0x94, 0x50, 0x3c, 0x84, 0x70, 0xbf, 0x63, 0xd7, 0x99, 0x0c, 0xf7, 0x3b,
	0xda, 0x29, 0xb1, 0xad, 0xce, 0x47, 0xf5, 0x0d, 0x1b, 0x36, 0x9e, 0xc9, 0x01, 0x43, 0x7d, 0x1e,
	0xcf, 0x2d, 0x76, 0xe9, 0xa8, 0x16, 0x4f, 0x60, 0x76, 0x2c, 0x6b, 0x34, 0x36, 0xaf, 0x5b, 0x9f,
	0xef, 0x42, 0x88, 0x25, 0x4c, 0x0f, 0xea, 0x5e, 0x17, 0xb8, 0xdf, 0x25, 0x11, 0x8b, 0x3d, 0x26,
	0x37, 0x57, 0xf3, 0x99, 0x13, 0xe7, 0x76, 0x61, 0xe8, 0x06, 0xae, 0xb5, 0x56, 0x3a, 0x89, 0x59,
	0x72, 0x40, 0xac, 0x21, 0xae, 0xd1, 0x18, 0xba, 0xae, 0xe9, 0x2a, 0xc8, 0xe6, 0xdb, 0xab, 0xb5,
	0x9b, 0x1d, 0x47, 0x5a, 0xdf, 0x3a, 0x4d, 0x76, 0x8b, 0x96, 0x9f, 0x20, 0xf6, 0xdc, 0x3f, 0x71,
	0xbb, 0x38, 0xe1, 0x20, 0x0e, 0x71, 0xf8, 0xa3, 0x1f, 0x20, 0xd5, 0x14, 0x42, 0xa2, 0x69, 0x55,
	0x63, 0xd0, 0x27, 0xec, 0x71, 0xfa, 0x33, 0x80, 0x47, 0x1d, 0xb8, 0x29, 0x9b, 0xd3, 0x9b, 0xaa,
	0xa2, 0x81, 0x1f, 0xee, 0x8b, 0x02, 0x8d, 0x61, 0xb3, 0xa9, 0xec, 0x20, 0x29, 0xbe, 0x19, 0x6f,
	0xda, 0xf7, 0xf6, 0xcc, 0x3d, 0x05, 0xf6, 0x9d, 0x6f, 0xe7, 0x3e, 0x13, 0x51, 0xd2, 0xbd, 0x91,
	0xe7, 0x30, 0xe1, 0x84, 0x34, 0xd1, 0x51, 0x36, 0xdf, 0x2e, 0x86, 0xb1, 0xa5, 0xd7, 0xb6, 0xaf,
	0x61, 0xc1, 0xd5, 0xbb, 0xbc, 0x39, 0x55, 0xa8, 0xc5, 0x4b, 0x88, 0xbb, 0xae, 0x1e, 0xf8, 0x0d,
	0xee, 0x4d, 0x2f, 0x1f, 0x7b, 0xf8, 0x57, 0xf3, 0x77, 0x13, 0xfe, 0x07, 0x5e, 0xfd, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0xb4, 0xa9, 0x05, 0x7d, 0x2f, 0x03, 0x00, 0x00,
}
