// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AppServerFactory is an autogenerated mock type for the AppServerFactory type
type AppServerFactory struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *AppServerFactory) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Serve provides a mock function with given fields:
func (_m *AppServerFactory) Serve() {
	_m.Called()
}

// Shutdown provides a mock function with given fields: ctx
func (_m *AppServerFactory) Shutdown(ctx context.Context) {
	_m.Called(ctx)
}
