// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// JSONSchemaValidator is an autogenerated mock type for the JSONSchemaValidator type
type JSONSchemaValidator struct {
	mock.Mock
}

// ValidateDocument provides a mock function with given fields: schemaID, documentSource
func (_m *JSONSchemaValidator) ValidateDocument(schemaID string, documentSource interface{}) error {
	ret := _m.Called(schemaID, documentSource)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(schemaID, documentSource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJSONSchemaValidator creates a new instance of JSONSchemaValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJSONSchemaValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *JSONSchemaValidator {
	mock := &JSONSchemaValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
