// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	validator "github.com/golangid/candi/validator"
	mock "github.com/stretchr/testify/mock"
)

// JSONSchemaValidatorOptionFunc is an autogenerated mock type for the JSONSchemaValidatorOptionFunc type
type JSONSchemaValidatorOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *JSONSchemaValidatorOptionFunc) Execute(_a0 *validator.JSONSchemaValidator) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewJSONSchemaValidatorOptionFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewJSONSchemaValidatorOptionFunc creates a new instance of JSONSchemaValidatorOptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJSONSchemaValidatorOptionFunc(t mockConstructorTestingTNewJSONSchemaValidatorOptionFunc) *JSONSchemaValidatorOptionFunc {
	mock := &JSONSchemaValidatorOptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
