// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	validator "github.com/golangid/candi/validator"
	mock "github.com/stretchr/testify/mock"
)

// StructValidatorOptionFunc is an autogenerated mock type for the StructValidatorOptionFunc type
type StructValidatorOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *StructValidatorOptionFunc) Execute(_a0 *validator.StructValidator) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewStructValidatorOptionFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewStructValidatorOptionFunc creates a new instance of StructValidatorOptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStructValidatorOptionFunc(t mockConstructorTestingTNewStructValidatorOptionFunc) *StructValidatorOptionFunc {
	mock := &StructValidatorOptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
