// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	types "pkg.agungdp.dev/candi/codebase/factory/types"
)

// WorkerHandlerOptionFunc is an autogenerated mock type for the WorkerHandlerOptionFunc type
type WorkerHandlerOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *WorkerHandlerOptionFunc) Execute(_a0 *types.WorkerHandler) {
	_m.Called(_a0)
}
