// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WorkerHandlerFunc is an autogenerated mock type for the WorkerHandlerFunc type
type WorkerHandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, message
func (_m *WorkerHandlerFunc) Execute(ctx context.Context, message []byte) error {
	ret := _m.Called(ctx, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
