// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/golangid/candi/codebase/factory/types"
	mock "github.com/stretchr/testify/mock"
)

// WorkerErrorHandler is an autogenerated mock type for the WorkerErrorHandler type
type WorkerErrorHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, workerType, workerName, message, err
func (_m *WorkerErrorHandler) Execute(ctx context.Context, workerType types.Worker, workerName string, message []byte, err error) {
	_m.Called(ctx, workerType, workerName, message, err)
}
