// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	types "github.com/golangid/candi/codebase/factory/types"
	mock "github.com/stretchr/testify/mock"
)

// WorkerHandlerOptionFunc is an autogenerated mock type for the WorkerHandlerOptionFunc type
type WorkerHandlerOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *WorkerHandlerOptionFunc) Execute(_a0 *types.WorkerHandler) {
	_m.Called(_a0)
}
